version: '3'

services:
  sqldatabase:
    build: ./User-Reservation-api/MySQL Database
    environment:
      MYSQL_DATABASE: user-reservation
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - ./User-Reservation-api/MySQL Database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10

  memcached:
    image: memcached:1.6.16
    restart: always
    ports:
      - "11211:11211"

  user-reservation:
    build: ./User-Reservation-api/Backend
    deploy:
      replicas: 3
    depends_on:
      sqldatabase:
        condition: service_healthy
      memcached:
        condition: service_started
    ports:
      - "8002"

  user-reservationnginx:
    image: nginx:latest
    volumes:
      - ./User-Reservation-api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:8090"
    depends_on:
      - user-reservation

  mongodatabase:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 20s
      retries: 10

  hotel:
    build: ./Hotel-api/Backend
    deploy:
      replicas: 3
    volumes:
      - hotel_images:/API/Images
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodatabase:
        condition: service_started
    ports:
      - "8000"

  hotelnginx:
    image: nginx:latest
    volumes:
      - ./Hotel-api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - hotel

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    entrypoint:
      - "bash"
      - "-c"
      - "precreate-core hotels; exec solr -f"

  search:
    build: ./Search-api/Backend
    deploy:
      replicas: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
      solr:
        condition: service_started
    ports:
      - "8001"

  searchnginx:
    image: nginx:latest
    volumes:
      - ./Search-api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8085:8085"
    depends_on:
      - search

  frontend:
    build: ./Frontend/miranda-hotels
    ports:
      - "5173:5173"

volumes:
  hotel_images: